const { gql } = require('apollo-server')

/**
 * typeDefs
 * Document or documents that represent your server's GraphQL schema,
 * generated by applying the gql tag to valid Schema Definition
 * Language (SDL) strings.
 *
 * Required unless you provide schema.
 */

const typeDefs = gql`
  type User {
    id: ID!
    name: String!
    username: String!
    age: Int!
    nationality: String!
  }

  type Query {
    users: [User!]!
  }
`

module.exports = { typeDefs }
